name: Test Docker Compose

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
        # ports:
        #   - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
  
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # - name: Build app image
      #   run: docker build -t test-app .

      - name: Pull pre-built app image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/worling-docker:latest
        
      - name: Run app and test DB connection
        run: docker run --rm --net host ${{ secrets.DOCKER_USERNAME }}/worling-docker:latest}}